### ISSUE TITLE
problem with deploy

### ISSUE THREAD

**Issue by suppix** [benmfaul/XRTB#6]
Hello. 
Thank you for your work. 

I have several problems with deploy. Could you please help me?

1) 
```
# tools/load-database
Exception in thread "main" com.aerospike.client.AerospikeException$Timeout: Client timeout: timeout=0 iterations=2 failedNodes=2 failedConns=0
```
in spite of I have a valid ip address in payday.json:
```
             "aerospike": {^M
                        "host": "xx.xxx.xxx.xxx",^M
```

2) Campaigns/payday.json
```
"adx": "<a href='locahost:8080   
```
locahost  - should be localhost or external ip?

3) 
```
# tools/rtb4free
java.lang.Exception: java.io.FileNotFoundException: /home/ben/Downloads/CIDR.txt (No such file or directory)
```

Where can I find CIDR.txt ? 

 Thank you.

**Comment by benmfaul** [comment]
Hello:

1. Aerospike issue. Is the aerospike server running at xx.xxx.xxx.xxx?
Is it firewalled perhaps - is port 3000 available?

2. If you are testing all within your own system you can use localhost. If
you are sending
bids from an external host, you need to use an IP address that is visible
to the outside world.

3. In payday.json, delete the lists object. You don't need it, I was
testing and accidently checked it in. It is corrected now if you do a git
pull.

-Ben Faul

**Comment by suppix** [comment]
Thank you for the reply. 

1) Yes aerospike is available at x.x.x.x 3000, I have checked using telnet x.x.x.x 3000 and it's ok. But when I use tcpdump to see the packets, I saw that rtb4free still tried to connect to localhost.

but in my payday.json 
```
      "aerospike": {^M
                        "host": "x.x.x.x",^M
                        "port": 3000^M
                },^M
```
```
telnet x.x.x.x 3000
Trying x.x.x.x...
Connected to x.x.x.x.
Escape character is '^]'.
```

**Comment by benmfaul** [comment]
Suppix:

Did you load the database first:

$tools/load-database -aero xx.xx.xx.xx:3000 -db database.json

Did this work?

If so it would have printed the value of database.json to stdout.

---------------------
I added a printout that says where RTB4FREE is connecting to aerospike.

Do a git pull and rebuild with maven.

When it starts it will look like this when you start:

$tools/rtb4free

*** Aerospike connection set to: 192.168.1.166:3000 ***
[2016-12-29 17:44:58.707] - 1 - ben-ThinkStation-S20:8080 -
initialization:campaign - Loaded  User/Campaign ben:payday/ben:payday
[2016-12-29 17:44:58.711] - 1 - ben-ThinkStation-S20:8080 - Configuration -
*** WIN URL IS SET TO LOCALHOST, NO REMOTE ACCESS WILL WORK FOR WINS ***
*** Shut Down Hook Attached. ***
log4j:WARN No appenders could be found for logger
(org.eclipse.jetty.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
more info.
[2016-12-29 17:44:58.820] - 1 - ben-ThinkStation-S20:8080 - RTBServer.run -
SSL configured on port 8081
[2016-12-29 17:44:59.848] - 1 - ben-ThinkStation-S20:8080 - Heartbeat -
cpu=6.166%, mem=50M (1.846%), freedsk=89.849%, threads=63, low-on-threads=
false, qps=0.00, avgBidTime=0.00ms, avgForensiq= 0ms, total=0, requests=0,
bids=0, nobids=0, fraud=0, wins=0, pixels=0, clicks=0, stopped=false,
campaigns=1
[2016-12-29 17:45:00.639] - 1 - ben-ThinkStation-S20:8080 - initialization
- System start on port: 8080


--------------------

Make sure you are referencing the correct payday.json file. You have a
configuration issue.

------------------

If you are still having problems, you could grant me temporary access to
your system and I will see what the problem is.


-Ben Faul
